name: "Lock Branch"
description: 'Locks a branch using GitHub Branch Protection Rules.'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  org-name:
    description: 'Organisation Name'
    required: true
  repo-name:
    description: 'Repository Name'
    required: true
  branch-name:
    description: 'Branch Name'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'